# Lab 3 - Numpy

### np.array 

In [1]:
#import
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
l1 = [2,3,4,5]
l2 = [3,4,5,6]
b = np.array([l1,l2])
print(b)

[[2 3 4 5]
 [3 4 5 6]]


In [4]:
x  = list(range(3))
y = np.array(x)
print(x)
print(sum(x))
print(y)
print(np.sum(y))

[0, 1, 2]
3
[0 1 2]
3


In [5]:
z = np.array(range(4))
print(z)

[0 1 2 3]


### 2-D array 

In [6]:
mat = np.array([[1,2,3],[2.3,'hello', 3]])
print(mat)

[['1' '2' '3']
 ['2.3' 'hello' '3']]


### Dimension, shape,  size and other methods

In [13]:
mat2 = np.array([[1,2,3,5],[4,2.3,'hello', 'ITER']])
print(mat2)
print("dimension: ",mat2.ndim)
print("Shape: ",mat2.shape)
print("Size: ",mat2.size)

[['1' '2' '3' '5']
 ['4' '2.3' 'hello' 'ITER']]
dimension:  2
Shape:  (2, 4)
Size:  8


In [14]:
arr1 = np.ones(7)
print(arr1)

[1. 1. 1. 1. 1. 1. 1.]


In [16]:
arr2 = np.arange(1,17)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [17]:
arr3 = np.full((2,3),10)
print(arr3)

[[10 10 10]
 [10 10 10]]


In [35]:
arr4 = np.arange(5)
arr5 = np.ones(5)
print(arr4)
print(arr5)
print(arr4.dtype)
print(arr5.dtype)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]
int64
float64


dtype('float64')

#### WAP to define 2  numpy array and display its addition. 

In [44]:
arr10 = np.array([list(range(1,6)),list(range(6,11))])
arr11 = np.array([list(range(11,16)),list(range(16,21))])
res1 = arr10 + arr11
print(arr10,"\n\n")
print(arr11,"\n\n")
print(res1,"\n\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 


[[11 12 13 14 15]
 [16 17 18 19 20]] 


[[12 14 16 18 20]
 [22 24 26 28 30]] 




In [45]:
arr12 = np.random.randint(0,10,5)
arr13 = np.random.randint(0,10,5)
res2 = arr12 + arr13
print(arr12,"\n\n")
print(arr13,"\n\n")
print(res2,"\n\n")

[7 0 2 3 5] 


[1 5 4 8 7] 


[ 8  5  6 11 12] 




#### WAP 2 array, compare each no, find how many times arr1 was greater  

In [51]:
arr20 =  np.random.randint(0,101,10)
arr21 =  np.random.randint(0,101,10)
no_of_times = 0
for i in range(10):
    if(arr20[i]>arr21[i]):
        no_of_times += 1

print(arr20,"\n\n")
print(arr21,"\n\n")        
print(no_of_times)


[69 17  9 42 55 11 39 85 59  2] 


[33 23 56 28 75 97 25 13 15 68] 


5


#### WAP to find avg marks, and marks above avg 

In [55]:
arr30 =  np.random.randint(30,101,10)

avg_marks = np.sum(arr30)/10

print(arr30,"\n\n")
print("avg marks = ", avg_marks)
for i in range(10):
    if(arr30[i]>= avg_marks):
        print(f"student{i} has scored: {arr30[i]}")

[62 94 66 59 58 32 57 89 50 74] 


avg marks =  64.1
student1 has scored: 94
student2 has scored: 66
student7 has scored: 89
student9 has scored: 74
