# Lab 3 - Numpy

### np.array 

In [1]:
#import
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
l1 = [2,3,4,5]
l2 = [3,4,5,6]
b = np.array([l1,l2])
print(b)

[[2 3 4 5]
 [3 4 5 6]]


In [4]:
x  = list(range(3))
y = np.array(x)
print(x)
print(sum(x))
print(y)
print(np.sum(y))

[0, 1, 2]
3
[0 1 2]
3


In [5]:
z = np.array(range(4))
print(z)

[0 1 2 3]


### 2-D array 

In [6]:
mat = np.array([[1,2,3],[2.3,'hello', 3]])
print(mat)

[['1' '2' '3']
 ['2.3' 'hello' '3']]


### Dimension, shape and size

In [13]:
mat2 = np.array([[1,2,3,5],[4,2.3,'hello', 'ITER']])
print(mat2)
print("dimension: ",mat2.ndim)
print("Shape: ",mat2.shape)
print("Size: ",mat2.size)

[['1' '2' '3' '5']
 ['4' '2.3' 'hello' 'ITER']]
dimension:  2
Shape:  (2, 4)
Size:  8
