## Lab 4 - Numpy Questions

In [1]:
import numpy as np

### reshape and ravel


#### 3X4 Array | consecutive no. 1-12 | use reshape() and ravel() 

In [2]:
arr1 = np.array([list(range(1,5)),list(range(5,9)),list(range(9,13))])

arr2 = arr1.reshape(2,6)
arr3 = arr1.ravel()

print(arr1,"\n")
print(arr2,"\n")
print(arr3,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 



In [3]:
arr4 = np.arange(1,13).reshape(3,4)


arr5 = arr4.reshape(4,3)
arr6 = arr4.ravel()
arr7 = arr4.reshape(1,-1)

print(arr4,"\n")
print(arr5,"\n")
print(arr6,"\n")
print(arr7,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 



#### Roll dice 1000 times | numpy randint | count freq of each outcome | display as dict {face --> count}

In [29]:
rolls = np.random.randint(1,7,1000)

#freq = {i: np.sum(rolls == i) for i in range(1,7)}
freq = {}
for i in range(1,7):
    freq[i] = np.sum(rolls == i)
print(freq)

{1: 173, 2: 163, 3: 184, 4: 169, 5: 142, 6: 169}
