## Lab 4 - Numpy Questions

In [1]:
import numpy as np

### reshape and ravel


#### 3X4 Array | consecutive no. 1-12 | use reshape() and ravel() 

In [2]:
arr1 = np.array([list(range(1,5)),list(range(5,9)),list(range(9,13))])

arr2 = arr1.reshape(2,6)
arr3 = arr1.ravel()

print(arr1,"\n")
print(arr2,"\n")
print(arr3,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 



In [3]:
arr4 = np.arange(1,13).reshape(3,4)


arr5 = arr4.reshape(4,3)
arr6 = arr4.ravel()
arr7 = arr4.reshape(1,12)

print(arr4,"\n")
print(arr5,"\n")
print(arr6,"\n")
print(arr7,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 



#### Roll dice 1000 times | numpy randint | count freq of each outcome | display as dict {face --> count}

In [4]:
rolls = np.random.randint(1,7,1000)

#freq = {i: np.sum(rolls == i) for i in range(1,7)}
freq = {}
for i in range(1,7):
    freq[i] = np.sum(rolls == i)
print(freq)

{1: 178, 2: 147, 3: 163, 4: 172, 5: 178, 6: 162}


#### for 2 matrix find | Multiplication | determinant | inverse 

In [13]:
matA = np.random.randint(0,5,9).reshape(3,3)
matB = np.random.randint(0,5,9).reshape(3,3)

print("Matrix A :\n",matA, "\n")
print("Matrix B :\n",matB, "\n")

mul = np.dot(matA, matB)

detA = np.linalg.det(matA)
detB = np.linalg.det(matB)

invA = 0
invB = 0

if (detA != 0):
    invA = np.linalg.inv(matA)

if (detB != 0):
    invB = np.linalg.inv(matB)


print("Multiplication -- Matrix A X Matrix B:\n",mul, "\n")

print("Deteminant 0f Matrix A : ",detA, "\n")
print("Deteminant 0f Matrix B : ",detB, "\n")

print("Inverse 0f Matrix A :\n",invA, "\n")
print("Inverse 0f Matrix B :\n",invB, "\n")



Matrix A :
 [[4 2 0]
 [0 2 2]
 [3 3 0]] 

Matrix B :
 [[2 1 1]
 [4 2 0]
 [0 1 0]] 

Multiplication -- Matrix A X Matrix B:
 [[16  8  4]
 [ 8  6  0]
 [18  9  3]] 

Deteminant 0f Matrix A :  -11.999999999999995 

Deteminant 0f Matrix B :  4.0 

Inverse 0f Matrix A :
 [[ 0.5         0.         -0.33333333]
 [-0.5         0.          0.66666667]
 [ 0.5         0.5        -0.66666667]] 

Inverse 0f Matrix B :
 [[ 0.    0.25 -0.5 ]
 [ 0.    0.    1.  ]
 [ 1.   -0.5   0.  ]] 

